server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.100:5432/ecommerce_auth
    username: postgres
    password: chungnt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: your_very_long_and_secure_secret_key_which_is_at_least_64_characters_long_to_meet_hs512_requirements
  expiration: 3600000